data-sources:
    bp:
        url: https://www.bp.com/content/dam/bp/business-sites/en/global/corporate/xlsx/energy-economics/statistical-review/bp-stats-review-2022-all-data.xlsx
        sheet_names:
            energy: Primary Energy Consumption
            emissions: CO2 Emissions from Energy
    worldbank:
        urls:
            population: https://api.worldbank.org/v2/en/indicator/SP.POP.TOTL?downloadformat=csv
            gdp: https://api.worldbank.org/v2/en/indicator/NY.GDP.MKTP.KD?downloadformat=csv
    iea:
        path: data/GHGHighlights.XLS
    maddison:
        url: https://www.rug.nl/ggdc/historicaldevelopment/maddison/data/mpd2020.xlsx
        sheet_names:
            gdp_per_capita: "GDP pc"
            population: "Population"
        countries:
            - CZE
            - HUN
            - SVK
            - LVA
            - EST
            - POL
            - RUS
            - LTU
    flags:
        url: https://github.com/hampusborgos/country-flags/blob/main/png100px/{country}.png?raw=true
countries:
    - Austria
    - Australia
    - Belgium
    - Canada
    - Chile
    - Colombia
    - Czech Republic
    - Denmark
    - Estonia
    - Finland
    - France
    - Germany
    - Greece
    - Hungary
    - Iceland
    - Ireland
    - Israel
    - Italy
    - Japan
    - Korea, Republic of
    - Latvia
    - Lithuania
    - Luxembourg
    - Mexico
    - Netherlands
    - New Zealand
    - Norway
    - Poland
    - Portugal
    - Slovakia
    - Slovenia
    - Spain
    - Sweden
    - Switzerland
    - Turkey
    - United Kingdom
    - US
    - Argentina
    - Brazil
    - China
    - Indonesia
    - India
    - Russian Federation
    - South Africa
    - Saudi Arabia
    - OECD
    - Non-OECD
    - World
crises:
    covid-crisis:
        name: COVID-19 pandemic
        global:
            pre-from-year: 2010
            first-year: 2020
            final-year: 2021
            post-to-year: 2021
    financial-crisis:
        name: Global Financial Crisis
        global:
            pre-from-year: 1998
            first-year: 2008
            final-year: 2009
            post-to-year: 2019
        national:
            PRT:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2013
                post-to-year: 2019
            FIN:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2014
                post-to-year: 2019
            AUT:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2009
                post-to-year: 2019
            NOR:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2009
                post-to-year: 2019
            USA:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2009
                post-to-year: 2019
            ITA:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2014
                post-to-year: 2019
            NLD:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2009
                post-to-year: 2019
            JPN:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2009
                post-to-year: 2019
            IRL:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2009
                post-to-year: 2019
            ESP:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2013
                post-to-year: 2019
            SVN:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2009
                post-to-year: 2019
            GRC:
                pre-from-year: 1998
                first-year: 2008
                final-year: 2016
                post-to-year: 2019
    soviet-union-collapse:
        name: Soviet Union’s collapse and Nordic countries’ Financial crisis
        global:
            pre-from-year: 1980
            first-year: 1990
            final-year: 1991
            post-to-year: 2001
        national:
            SVK:
                pre-from-year: 1985
                first-year: 1990
                final-year: 1992
                post-to-year: 2002
            LVA:
                pre-from-year: 1985
                first-year: 1991
                final-year: 1993
                post-to-year: 2003
            EST:
                pre-from-year: 1985
                first-year: 1990
                final-year: 1994
                post-to-year: 2004
            POL:
                pre-from-year: 1985
                first-year: 1989
                final-year: 1991
                post-to-year: 2001
            RUS:
                pre-from-year: 1985
                first-year: 1990
                final-year: 1998
                post-to-year: 2008
            LTU:
                pre-from-year: 1985
                first-year: 1989
                final-year: 1994
                post-to-year: 2004
    first-oil-crisis:
        name: First oil crisis
        global:
            pre-from-year: 1965
            first-year: 1974
            final-year: 1975
            post-to-year: 1979 # to not overlap with the Second oil crisis
        national:
            BEL:
                pre-from-year: 1965
                first-year: 1974
                final-year: 1975
                post-to-year: 1979
            GBR:
                pre-from-year: 1965
                first-year: 1974
                final-year: 1975
                post-to-year: 1979
            LUX:
                pre-from-year: 1965
                first-year: 1974
                final-year: 1975
                post-to-year: 1979
    second-oil-crisis:
        name: Second oil crisis
        global:
            pre-from-year: 1976
            first-year: 1980
            final-year: 1981
            post-to-year: 1991
        national:
            SWE:
                pre-from-year: 1976
                first-year: 1980
                final-year: 1981
                post-to-year: 1990
            DEU:
                pre-from-year: 1976
                first-year: 1980
                final-year: 1982
                post-to-year: 1992
            FRA:
                pre-from-year: 1976
                first-year: 1980
                final-year: 1981
                post-to-year: 1991
            CZE:
                pre-from-year: 1976
                first-year: 1981
                final-year: 1982
                post-to-year: 1990
            HUN:
                pre-from-year: 1976
                first-year: 1979
                final-year: 1979
                post-to-year: 1988
    brazilian-crisis:
        name: National crisis of Brazil
        global:
            pre-from-year: 2010
            first-year: 2015
            final-year: 2015
            post-to-year: 2019
    argentinian-crisis:
        name: National crisis of Argentina
        global:
            pre-from-year: 2012
            first-year: 2016
            final-year: 2016
            post-to-year: 2019
    denmark-peak:
        name: Period surrounding Denmark's emission peak (not a crisis)
        global:
            pre-from-year: 1988
            first-year: 1998
            final-year: 1998
            post-to-year: 2008
    switzerland-peak:
        name: Period surrounding Switzerland's emission peak (not a crisis)
        global:
            pre-from-year: 1991
            first-year: 2001
            final-year: 2001
            post-to-year: 2011
    entire-period:
        name: A period covering all years
        global:
            pre-from-year: 1968
            first-year: 2000
            final-year: 2000
            post-to-year: 2019
highlights:
    peak-and-decline:
        first-oil-crisis:
            - BEL
            - GBR
            - LUX
        second-oil-crisis:
            - SWE
            - DEU
            - FRA
            - CZE
            - HUN
        soviet-union-collapse:
            - SVK
            - LVA
            - EST
            - POL
            - RUS
            - LTU
        financial-crisis:
            - PRT
            - FIN
            - AUT
            - NOR
            - USA
            - ITA
            - NLD
            - JPN
            - IRL
            - ESP
            - SVN
            - GRC
    no-peak-and-decline-timeline:
        financial-crisis:
            - AUS
            - ISR
            - ZAF
            - ARG
            - BRA
            - MEX
            - SAU
            - TUR
            - KOR
            - ISL
            - CHL
            - CHN
            - COL
            - IDN
            - IND
            - CAN
            - NZL
    no-peak-and-decline-prepost:
        soviet-union-collapse:
            - ARG
            - AUS
            - BRA
            - CHL
            - CHN
            - COL
            - IDN
            - IND
            - KOR
            - MEX
            - NZL
            - SAU
            - TUR
            - ZAF
        financial-crisis:
            - AUS
            - ISR
            - ZAF
            - ARG
            - BRA
            - MEX
            - SAU
            - TUR
            - KOR
            - ISL
            - CHL
            - CHN
            - COL
            - IDN
            - IND
            - CAN
            - NZL
    all:
        entire-period:
            - AUS
            - AUT
            - BEL
            - CAN
            - CHL
            - COL
            - CZE
            - DNK
            - EST
            - FIN
            - FRA
            - DEU
            - GRC
            - HUN
            - ISL
            - IRL
            - ISR
            - ITA
            - JPN
            - KOR
            - LVA
            - LTU
            - LUX
            - MEX
            - NLD
            - NZL
            - NOR
            - POL
            - PRT
            - SVK
            - SVN
            - ESP
            - SWE
            - CHE
            - TUR
            - GBR
            - USA
            - ARG
            - BRA
            - CHN
            - IDN
            - IND
            - RUS
            - ZAF
            - SAU
    non-crisis-peaker:
        denmark-peak:
            - DNK
        switzerland-peak:
            - CHE
    peaks:
        peak-and-decline:
            first-oil-crisis:
                - BEL
                - GBR
                - LUX
            second-oil-crisis:
                - SWE
                - DEU
                - FRA
                - CZE
                - HUN
            soviet-union-collapse:
                - SVK
                - LVA
                - EST
                - POL
                - RUS
                - LTU
            financial-crisis:
                - PRT
                - FIN
                - AUT
                - NOR
                - USA
                - ITA
                - NLD
                - JPN
                - IRL
                - ESP
                - SVN
                - GRC
        no-peak-and-decline:
            first-oil-crisis:
                - AUS
                - AUT
                - ARG
                - BRA
                - CAN
                - CHL
                - CHN
                - COL
                - CZE
                - DEU
                - DNK
                - ESP
                - EST
                - FIN
                - FRA
                - GRC
                - HUN
                - IDN
                - IND
                - IRL
                - ISL
                - ISR
                - ITA
                - JPN
                - KOR
                - LTU
                - LVA
                - MEX
                - NLD
                - NOR
                - NZL
                - POL
                - PRT
                - RUS
                - SAU
                - SVK
                - SVN
                - SWE
                - TUR
                - CHE
                - USA
                - ZAF
            second-oil-crisis:
                - AUS
                - AUT
                - ARG
                - BRA
                - CAN
                - CHL
                - CHN
                - COL
                - DNK
                - ESP
                - EST
                - FIN
                - GRC
                - IDN
                - IND
                - IRL
                - ISL
                - ISR
                - ITA
                - JPN
                - KOR
                - LTU
                - LVA
                - MEX
                - NLD
                - NOR
                - NZL
                - POL
                - PRT
                - RUS
                - SAU
                - SVK
                - SVN
                - TUR
                - CHE
                - USA
                - ZAF
            soviet-union-collapse:
                - AUS
                - AUT
                - ARG
                - BRA
                - CAN
                - CHL
                - CHN
                - COL
                - DNK
                - ESP
                - FIN
                - GRC
                - IDN
                - IND
                - IRL
                - ISL
                - ISR
                - ITA
                - JPN
                - KOR
                - MEX
                - NLD
                - NOR
                - NZL
                - PRT
                - SAU
                - SVN
                - TUR
                - CHE
                - USA
                - ZAF
            financial-crisis:
                - AUS
                - ARG
                - BRA
                - CAN
                - CHL
                - CHN
                - COL
                - IDN
                - IND
                - ISL
                - ISR
                - KOR
                - MEX
                - NZL
                - SAU
                - TUR
                - ZAF
        peaked-before:
            first-oil-crisis:
            second-oil-crisis:
                - BEL
                - GBR
                - LUX
            soviet-union-collapse:
                - BEL
                - GBR
                - LUX
                - SWE
                - DEU
                - FRA
                - CZE
                - HUN
            financial-crisis:
                - BEL
                - GBR
                - LUX
                - SWE
                - DEU
                - FRA
                - CZE
                - HUN
                - SVK
                - LVA
                - EST
                - POL
                - RUS
                - LTU
                - CHE
                - DNK
groups:
    high-income:
        - AUS
        - AUT
        - BEL
        - CAN
        - CHL
        - CZE
        - DEU
        - DNK
        - ESP
        - EST
        - FIN
        - FRA
        - GBR
        - GRC
        - HUN
        - IRL
        - ISL
        - ISR
        - ITA
        - JPN
        - KOR
        - LTU
        - LUX
        - LVA
        - NLD
        - NOR
        - NZL
        - POL
        - PRT
        - SAU
        - SVK
        - SVN
        - SWE
        - CHE
        - USA
    middle-income:
        - ARG
        - BRA
        - CHN
        - COL
        - IDN
        - IND
        - MEX
        - RUS
        - TUR
        - ZAF
push-directory: ~/Documents/work/Shared
