bp:
    path: data/bp-stats-review-2020-all-data.xlsx
    sheetnames:
        energy: Primary Energy Consumption
        emissions: Carbon Dioxide Emissions
worldbank:
    paths:
        population: data/population/API_SP.POP.TOTL_DS2_en_csv_v2_1217749.csv
        gdp: data/gdp-constant/API_NY.GDP.MKTP.KD_DS2_en_csv_v2_1495282.csv
countries:
    - Austria
    - Australia
    - Belgium
    - Canada
    - Chile
    - Colombia
    - Czech Republic
    - Denmark
    - Estonia
    - Finland
    - France
    - Germany
    - Greece
    - Hungary
    - Iceland
    - Ireland
    - Israel
    - Italy
    - Japan
    - Korea, Republic of
    - Latvia
    - Lithuania
    - Luxembourg
    - Mexico
    - Netherlands
    - New Zealand
    - Norway
    - Poland
    - Portugal
    - Slovakia
    - Slovenia
    - Spain
    - Sweden
    - Switzerland
    - Turkey
    - United Kingdom
    - US
    - Argentina
    - Brazil
    - China
    - Indonesia
    - India
    - Russian Federation
    - South Africa
    - Saudi Arabia
    - OECD
    - Non-OECD
    - World
crises:
    financial-crisis:
        name: Global Financial Crisis
        pre-from-year: 1998
        first-year: 2008
        final-year: 2009
        post-to-year: 2018
    soviet-union-collapse:
        name: Soviet Union’s collapse and Nordic countries’ Financial crisis
        pre-from-year: 1980
        first-year: 1990
        final-year: 1991
        post-to-year: 2000
    first-oil-crisis:
        name: First oil crisis
        pre-from-year: 1966 # no energy intensity data available before that
        first-year: 1973
        final-year: 1975
        post-to-year: 1979 # to not overlap with the Second oil crisis
    second-oil-crisis:
        name: Second oil crisis
        pre-from-year: 1975
        first-year: 1979
        final-year: 1980
        post-to-year: 1985
    brazil:
        name: National crisis of Brazil
        pre-from-year: 2010
        first-year: 2015
        final-year: 2015
        post-to-year: 2020
    argentina:
        name: National crisis of Argentina
        pre-from-year: 2011
        first-year: 2016
        final-year: 2016
        post-to-year: 2020
