data-sources:
    bp:
        url: https://www.bp.com/content/dam/bp/business-sites/en/global/corporate/xlsx/energy-economics/statistical-review/bp-stats-review-2021-all-data.xlsx
        sheetnames:
            energy: Primary Energy Consumption
            emissions: Carbon Dioxide Emissions
    worldbank:
        urls:
            population: https://api.worldbank.org/v2/en/indicator/SP.POP.TOTL?downloadformat=csv
            gdp: https://api.worldbank.org/v2/en/indicator/NY.GDP.MKTP.KD?downloadformat=csv
    iea:
        path: data/GHGHighlights.XLS
countries:
    - Austria
    - Australia
    - Belgium
    - Canada
    - Chile
    - Colombia
    - Czech Republic
    - Denmark
    - Estonia
    - Finland
    - France
    - Germany
    - Greece
    - Hungary
    - Iceland
    - Ireland
    - Israel
    - Italy
    - Japan
    - Korea, Republic of
    - Latvia
    - Lithuania
    - Luxembourg
    - Mexico
    - Netherlands
    - New Zealand
    - Norway
    - Poland
    - Portugal
    - Slovakia
    - Slovenia
    - Spain
    - Sweden
    - Switzerland
    - Turkey
    - United Kingdom
    - US
    - Argentina
    - Brazil
    - China
    - Indonesia
    - India
    - Russian Federation
    - South Africa
    - Saudi Arabia
    - OECD
    - Non-OECD
    - World
crises:
    financial-crisis:
        name: Global Financial Crisis
        pre-from-year: 1998
        first-year: 2008
        final-year: 2009
        post-to-year: 2017
    soviet-union-collapse:
        name: Soviet Union’s collapse and Nordic countries’ Financial crisis
        pre-from-year: 1980
        first-year: 1990
        final-year: 1991
        post-to-year: 2000
    first-oil-crisis:
        name: First oil crisis
        pre-from-year: 1968
        first-year: 1974
        final-year: 1975
        post-to-year: 1979 # to not overlap with the Second oil crisis
    second-oil-crisis:
        name: Second oil crisis
        pre-from-year: 1975
        first-year: 1980
        final-year: 1980
        post-to-year: 1984
    brazilian-crisis:
        name: National crisis of Brazil
        pre-from-year: 2010
        first-year: 2015
        final-year: 2015
        post-to-year: 2019
    argentinian-crisis:
        name: National crisis of Argentina
        pre-from-year: 2012
        first-year: 2016
        final-year: 2016
        post-to-year: 2019
