bp:
    path: data/bp-stats-review-2020-all-data.xlsx
    sheetnames:
        energy: Primary Energy Consumption
        emissions: Carbon Dioxide Emissions
worldbank:
    paths:
        population: data/population/API_SP.POP.TOTL_DS2_en_csv_v2_1217749.csv
        gdp: data/gdp-constant/API_NY.GDP.MKTP.KD_DS2_en_csv_v2_1495282.csv
report:
    r2_threshold: 0.5
    p_value_threshold: 0.05
countries:
    - US
    - United Arab Emirates
    - Argentina
    - Australia
    - Austria
    - Azerbaijan
    - Belgium
    - Bangladesh
    - Bulgaria
    - Belarus
    - Brazil
    - Canada
    - Switzerland
    - Chile
    - China
    - Colombia
    - Cyprus
    - Czech Republic
    - Germany
    - Denmark
    - Algeria
    - Ecuador
    - Egypt
    - Spain
    - Estonia
    - Finland
    - France
    - United Kingdom
    - Greece
    - Croatia
    - Hong Kong
    - Hungary
    - Indonesia
    - India
    - Ireland
    - Iraq
    - Iceland
    - Israel
    - Italy
    - Japan
    - Kazakhstan
    - Kuwait
    - Sri Lanka
    - Lithuania
    - Luxembourg
    - Latvia
    - Morocco
    - Mexico
    - North Macedonia
    - Malaysia
    - Netherlands
    - Norway
    - New Zealand
    - Oman
    - Pakistan
    - Peru
    - Philippines
    - Poland
    - Portugal
    - Qatar
    - Romania
    - Russian Federation
    - Saudi Arabia
    - Singapore
    - Slovakia
    - Slovenia
    - Sweden
    - Thailand
    - Turkmenistan
    - Trinidad and Tobago
    - Turkey
    - Ukraine
    - Uzbekistan
    - Venezuela
    - South Africa
    - OECD
    - Non-OECD
    - World

    #- USSR FIX no worldbank data available
    #- Korea, Republic of TODO no emissions data
    #- Uruguay TODO no emissions data
crises:
    financial-crisis:
        name: Global Financial Crisis
        pre-from-year: 1998
        from-year: 2008
        to-year: 2009
        post-to-year: 2019
        countries:
            - United Arab Emirates
            - Argentina
            - Australia
            - Austria
            - Belgium
            - Bulgaria
            - Brazil
            - Canada
            - Switzerland
            - Chile
            - Germany
            - Denmark
            - Algeria
            - Ecuador
            - Estonia
            - France
            - United Kingdom
            - Hong Kong
            - Hungary
            - Ireland
            - Iceland
            - Israel
            - Japan
            - Kazakhstan
            - Kuwait
            - Lithuania
            - Luxembourg
            - Latvia
            - Mexico
            - North Macedonia
            - Malaysia
            - Norway
            - New Zealand
            - Philippines
            - Romania
            - Russian Federation
            - Saudi Arabia
            - Singapore
            - Slovakia
            - Sweden
            - Thailand
            - Trinidad and Tobago
            - Turkey
            - Ukraine
            - United States
            - South Africa
            - OECD
            - Non-OECD
            - World
    financial-and-euro-crisis:
        name: Global Financial & Euro-Crisis
        pre-from-year: 1998
        from-year: 2008
        to-year: 2013
        post-to-year: 2019
        countries:
            - Cyprus
            - Czechia
            - Spain
            - Finland
            - Greece
            - Croatia
            - Italy
            - Netherlands
            - Portugal
            - Slovenia
    asian-financial-crisis:
        name: Asian Financial Crisis
        pre-from-year: 1988
        from-year: 1998
        to-year: 1998
        post-to-year: 2009
        countries:
            - Indonesia
            #- Korea, Republic of TODO no emissions data
            - Thailand
            - Hong Kong
            - Malaysia
    argentinean-great-depression:
        name: Argentinean Great Depression
        pre-from-year: 1989
        from-year: 1999
        to-year: 2002
        post-to-year: 2013
        countries:
            - Argentina
            #- Uruguay TODO no emissions data
    tequila-crisis:
        name: Tequila Crisis
        pre-from-year: 1985
        from-year: 1995
        to-year: 1995
        post-to-year: 2006
        countries:
            - Mexico
    all-crises:
        name: All Crisis
        pre-from-year: 1966
        from-year: 1967
        to-year: 2018
        post-to-year: 2019
        countries:
            - OECD
            - Non-OECD
            - World
