name: default
channels:
    - conda-forge
dependencies:
    - python=3.8
    - numpy=1.19.1
    - pandas=1.1.3
    - xarray=0.16.1
    - netcdf4=1.5.4
    - matplotlib=3.2.1
    - seaborn=0.11.0
    - xlrd=1.2.0
    - pwlf=2.0.4
