name: default
channels:
    - conda-forge
dependencies:
    - python=3.10
    - numpy=1.22.3
    - pandas=1.4.1
    - xarray=2022.3.0
    - netcdf4=1.5.8
    - matplotlib=3.5.1
    - seaborn=0.12.1
    - openpyxl=3.0.9
    - pwlf=2.0.4
    - country_converter=0.7.7
    - pycountry=20.7.3
